Project_1/mysite/food/urls.py
from . import views
from django.urls import path
app_name = 'food'
urlpatterns = [
    #/food/ home url
    #path('', views.index, name='index'),
    path('', views.ClassIndexView.as_view(), name='index'),
    #/food/1 item detail url
    path('<int:pk>/', views.ClassDetailView.as_view(), name='details'),
    #item
    path('item/', views.item, name='item'),
    #/food/add additem 
    path('add/', views.ClassCreateView.as_view(), name='create_item'),
    #/food/update/1 upadate a specific item
    path('update/<int:id>/', views.update_item, name='update_item'),
    #/ delete a specific item
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
]

Project_1/mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Item(models.Model):
    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=100)
    item_desc = models.CharField(max_length=300)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=1000, default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    def get_absolute_url(self):
        return reverse('food:details', kwargs={"pk":self.pk})

Project_1/mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

Project_1/mysite/food/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render,redirect
from food.models import Item

from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

#HOME VIEW + CLASS BASE VIEW
#def index(request):
#    item_list = Item.objects.all()
#    template = loader.get_template('food/index.html')
#    context  = {
#        'item_list':item_list,
#    }
#    return render(request, 'food/index.html', context)

class ClassIndexView(ListView):
    model =  Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


#NULL VIEW
def item(request):
    return HttpResponse("This is the item.")


#CREATE VIEW+CLASS CREATE VIEW
#def create_item(request):
   # form = ItemForm(request.POST or None)

   # if form.is_valid():
     #   form.save()
    #    return redirect('food:index')
    #return render(request, 'food/item-form.html', {'form':form})

class ClassCreateView(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        
        return super().form_valid(form)


#READ VIEW+CLASS READ VIEW

#def details(request,item_id):
#    item_details=Item.objects.get(pk=item_id)
#    context  = {
#        'item_details':item_details,
#    }
#    return render(request, 'food/details.html', context)


class ClassDetailView(DetailView):
    model =  Item
    template_name = 'food/details.html'
    context_object_name = 'item_details'



# UPADTE VIEW
def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form':form, 'item':item,})


# DELETE VIEW 
def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html', {'item':item})

Project_1/mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand"><img src="{% static 'food/images/pizza.webp' %}" alt="gif" width="40" height="40">FoodApp <img src="{% static 'food/images/hamburger_1f354.webp' %}" alt="gif" width="40" height="40"></a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Delete Item</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">View Item</a>
            </li>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>   
            {% endif %} 
        </ul>
        

    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
    
</body>
</html>

Project_1/mysite/food/templates/food/details.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="card" height="500px" width="500px" src="{{ item_details.item_image }}">
        </div>
        <div class="col-md-6">
            <h1>{{ item_details.item_name }}</h1>
            <h2>{{ item_details.item_desc }}</h2>
            <h3>${{ item_details.item_price }}</h3>
            <a href="{% url 'food:delete_item' item_details.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

Project_1/mysite/food/templates/food/index.html
<!DOCTYPE html>
{% extends 'food/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Items</title>
</head>
<body>
    {% block body %}
    {% for item in item_list %}
    <hr>
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="card" height="300px" width="300px" src="{{ item.item_image }}"/>
        </div>
        <div class="col-md-4">
            <h3>{{ item.item_name }}</h3>
            <h5>{{ item.item_desc }}</h5>
            <h6>${{ item.item_price }}</h6>
            <h6>{{ item.user_name }}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:details' item.pk %}" class="btn btn-success">Details</a>
        </div>
    </div>
    <hr> <marquee hspace="350px" behavior="scroll" direction="left"><strong class="sucess">20% Off on First Order</strong></marquee>
   {% endfor %}
   {% endblock %}
</body>
</html>

Project_1/mysite/food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete the {{item.item_name}}?</h2>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

Project_1/mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
 
{% block body %}
 
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form }}
 
                        <button class="btn-info" type="submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
 
</div>
{% endblock %}